### ISSUE TITLE
"Queue now" button is misleading

### ISSUE THREAD

**Issue by driehuis** [driehuis/retcon-web#2]
The "Queue now" button places the job in the queue of active jobs, effectively starting it immediately, bypassing the active jobs limit of the backup server. Both parts of this behavior are contrary to the Principle of Least Astonishment.

It has been like this for years so it's not fallout from the Rails 3.1 upgrade.

**Comment by autostatic** [comment]
This bug bit me so subscribing to this issue.

**Comment by driehuis** [comment]
Fixed in 1.0.8
